/*Load pricing table*/
insert into product_ks.product_price_by_tcin (tcin, currency_code, price, status) values (12345, 'USD', 10.99, 'ACTIVE');
insert into product_ks.product_price_by_tcin (tcin, currency_code, price, status) values (22345, 'USD', 20.99, 'ACTIVE');
insert into product_ks.product_price_by_tcin (tcin, currency_code, price, status) values (32345, 'USD', 30.99, 'ACTIVE');
insert into product_ks.product_price_by_tcin (tcin, currency_code, price, status) values (42345, 'USD', 40.99, 'ACTIVE');

